_base_: ../levircd.yaml

save_dir: ./exp/levircd/custom_model/iter2_gamma01/

model: !Node
    type: IterativeBIT
    args:
        num_iters: 2
        gamma: 0.1
        num_classes: 2
        bit_kwargs:
            in_channels: 4
