_base_: ../levircd.yaml

save_dir: ./exp/levircd/custom_model/iter3/

model: !Node
    type: IterativeBIT
    args:
        num_iters: 3
        num_classes: 2
        bit_kwargs:
            in_channels: 3
