_base_: ../levircd.yaml

save_dir: ./exp/levircd/custom_model/iter3_gamma02/

model: !Node
    type: IterativeBIT
    args:
        num_iters: 3
        gamma: 0.2
        num_classes: 2
        bit_kwargs:
            in_channels: 4
