_base_: ../levircd.yaml

save_dir: ./exp/custom_model/iter2_gamma02/

model: !Node
    type: IterativeBIT
    args:
        num_iters: 2
        gamma: 0.2
        num_classes: 2
        bit_kwargs:
            in_channels: 4
