_base_: ../levircd.yaml

save_dir: ./exp/custom_model/iter3_gamma10/

model: !Node
    type: IterativeBIT
    args:
        num_iters: 3
        gamma: 1.0
        num_classes: 2
        bit_kwargs:
            in_channels: 4
